es:
  node: 'http://localhost:9200'

redis:
  host: wsl.local
  port: 6379

wgwHost: 'http://127.0.0.1:9010'

userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0'
proxy:
  type: sock5
  host: 127.0.0.1
  port: 8023
#  type: http
#  host: 127.0.0.1
#  port: 18888

http:
  port: 20010

tempDir: "G:\\Wing\\Bt\\CrawlerTorrents"
